/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AssetResultModel model module.
 * @module model/AssetResultModel
 * @version 1.0.0
 */
class AssetResultModel {
    /**
     * Constructs a new <code>AssetResultModel</code>.
     * Asset result model
     * @alias module:model/AssetResultModel
     */
    constructor() { 
        
        AssetResultModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetResultModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetResultModel} obj Optional instance to populate.
     * @return {module:model/AssetResultModel} The populated <code>AssetResultModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetResultModel();

            if (data.hasOwnProperty('Message')) {
                obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
            }
            if (data.hasOwnProperty('AssetUrl')) {
                obj['AssetUrl'] = ApiClient.convertToType(data['AssetUrl'], 'String');
            }
            if (data.hasOwnProperty('AssetName')) {
                obj['AssetName'] = ApiClient.convertToType(data['AssetName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Asset result message
 * @member {String} Message
 */
AssetResultModel.prototype['Message'] = undefined;

/**
 * Asset URL or path
 * @member {String} AssetUrl
 */
AssetResultModel.prototype['AssetUrl'] = undefined;

/**
 * Asset name
 * @member {String} AssetName
 */
AssetResultModel.prototype['AssetName'] = undefined;






export default AssetResultModel;

