/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FlipdishOpenApiV10) {
      root.FlipdishOpenApiV10 = {};
    }
    root.FlipdishOpenApiV10.BusinessHoursPeriodBase = factory(root.FlipdishOpenApiV10.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The BusinessHoursPeriodBase model module.
   * @module model/BusinessHoursPeriodBase
   * @version v1.0
   */

  /**
   * Constructs a new <code>BusinessHoursPeriodBase</code>.
   * Business hours period
   * @alias module:model/BusinessHoursPeriodBase
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>BusinessHoursPeriodBase</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BusinessHoursPeriodBase} obj Optional instance to populate.
   * @return {module:model/BusinessHoursPeriodBase} The populated <code>BusinessHoursPeriodBase</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('DayOfWeek'))
        obj.dayOfWeek = ApiClient.convertToType(data['DayOfWeek'], 'String');
      if (data.hasOwnProperty('StartTime'))
        obj.startTime = ApiClient.convertToType(data['StartTime'], 'String');
      if (data.hasOwnProperty('Period'))
        obj.period = ApiClient.convertToType(data['Period'], 'String');
      if (data.hasOwnProperty('StartTimeEarly'))
        obj.startTimeEarly = ApiClient.convertToType(data['StartTimeEarly'], 'String');
      if (data.hasOwnProperty('PeriodEarly'))
        obj.periodEarly = ApiClient.convertToType(data['PeriodEarly'], 'String');
    }
    return obj;
  }

  /**
   * Day of week
   * @member {module:model/BusinessHoursPeriodBase.DayOfWeekEnum} dayOfWeek
   */
  exports.prototype.dayOfWeek = undefined;

  /**
   * Start time
   * @member {String} startTime
   */
  exports.prototype.startTime = undefined;

  /**
   * Period
   * @member {String} period
   */
  exports.prototype.period = undefined;

  /**
   * Start time early
   * @member {String} startTimeEarly
   */
  exports.prototype.startTimeEarly = undefined;

  /**
   * Period early
   * @member {String} periodEarly
   */
  exports.prototype.periodEarly = undefined;



  /**
   * Allowed values for the <code>dayOfWeek</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DayOfWeekEnum = {
    /**
     * value: "Sunday"
     * @const
     */
    sunday: "Sunday",

    /**
     * value: "Monday"
     * @const
     */
    monday: "Monday",

    /**
     * value: "Tuesday"
     * @const
     */
    tuesday: "Tuesday",

    /**
     * value: "Wednesday"
     * @const
     */
    wednesday: "Wednesday",

    /**
     * value: "Thursday"
     * @const
     */
    thursday: "Thursday",

    /**
     * value: "Friday"
     * @const
     */
    friday: "Friday",

    /**
     * value: "Saturday"
     * @const
     */
    saturday: "Saturday"
  };

  return exports;

}));
