/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DuringOrderPromotionOptionsDm model module.
 * @module model/DuringOrderPromotionOptionsDm
 * @version 1.0.0
 */
class DuringOrderPromotionOptionsDm {
    /**
     * Constructs a new <code>DuringOrderPromotionOptionsDm</code>.
     * @alias module:model/DuringOrderPromotionOptionsDm
     */
    constructor() { 
        
        DuringOrderPromotionOptionsDm.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DuringOrderPromotionOptionsDm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DuringOrderPromotionOptionsDm} obj Optional instance to populate.
     * @return {module:model/DuringOrderPromotionOptionsDm} The populated <code>DuringOrderPromotionOptionsDm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DuringOrderPromotionOptionsDm();

            if (data.hasOwnProperty('DuringOrderPromotionType')) {
                obj['DuringOrderPromotionType'] = ApiClient.convertToType(data['DuringOrderPromotionType'], 'String');
            }
            if (data.hasOwnProperty('MinSmsShareCount')) {
                obj['MinSmsShareCount'] = ApiClient.convertToType(data['MinSmsShareCount'], 'Number');
            }
            if (data.hasOwnProperty('FreeCokeCount')) {
                obj['FreeCokeCount'] = ApiClient.convertToType(data['FreeCokeCount'], 'Number');
            }
            if (data.hasOwnProperty('PromotionPeriodSeconds')) {
                obj['PromotionPeriodSeconds'] = ApiClient.convertToType(data['PromotionPeriodSeconds'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/DuringOrderPromotionOptionsDm.DuringOrderPromotionTypeEnum} DuringOrderPromotionType
 */
DuringOrderPromotionOptionsDm.prototype['DuringOrderPromotionType'] = undefined;

/**
 * @member {Number} MinSmsShareCount
 */
DuringOrderPromotionOptionsDm.prototype['MinSmsShareCount'] = undefined;

/**
 * @member {Number} FreeCokeCount
 */
DuringOrderPromotionOptionsDm.prototype['FreeCokeCount'] = undefined;

/**
 * @member {Number} PromotionPeriodSeconds
 */
DuringOrderPromotionOptionsDm.prototype['PromotionPeriodSeconds'] = undefined;





/**
 * Allowed values for the <code>DuringOrderPromotionType</code> property.
 * @enum {String}
 * @readonly
 */
DuringOrderPromotionOptionsDm['DuringOrderPromotionTypeEnum'] = {

    /**
     * value: "None"
     * @const
     */
    "None": "None",

    /**
     * value: "BumpFreeChocolate"
     * @const
     */
    "BumpFreeChocolate": "BumpFreeChocolate",

    /**
     * value: "BumpFreeCoke"
     * @const
     */
    "BumpFreeCoke": "BumpFreeCoke",

    /**
     * value: "SmsInviteFreeChocolate"
     * @const
     */
    "SmsInviteFreeChocolate": "SmsInviteFreeChocolate",

    /**
     * value: "SmsInviteFreeCoke"
     * @const
     */
    "SmsInviteFreeCoke": "SmsInviteFreeCoke"
};



export default DuringOrderPromotionOptionsDm;

