/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FlipdishFeesDetails model module.
 * @module model/FlipdishFeesDetails
 * @version 1.0.0
 */
class FlipdishFeesDetails {
    /**
     * Constructs a new <code>FlipdishFeesDetails</code>.
     * Fees breakdown
     * @alias module:model/FlipdishFeesDetails
     */
    constructor() { 
        
        FlipdishFeesDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FlipdishFeesDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FlipdishFeesDetails} obj Optional instance to populate.
     * @return {module:model/FlipdishFeesDetails} The populated <code>FlipdishFeesDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FlipdishFeesDetails();

            if (data.hasOwnProperty('OnlineSalesFees')) {
                obj['OnlineSalesFees'] = ApiClient.convertToType(data['OnlineSalesFees'], 'Number');
            }
            if (data.hasOwnProperty('CashSalesFees')) {
                obj['CashSalesFees'] = ApiClient.convertToType(data['CashSalesFees'], 'Number');
            }
            if (data.hasOwnProperty('PosSalesFees')) {
                obj['PosSalesFees'] = ApiClient.convertToType(data['PosSalesFees'], 'Number');
            }
            if (data.hasOwnProperty('TotalSalesFees')) {
                obj['TotalSalesFees'] = ApiClient.convertToType(data['TotalSalesFees'], 'Number');
            }
            if (data.hasOwnProperty('OnlineSalesRefundedFees')) {
                obj['OnlineSalesRefundedFees'] = ApiClient.convertToType(data['OnlineSalesRefundedFees'], 'Number');
            }
            if (data.hasOwnProperty('CashSalesRefundedFees')) {
                obj['CashSalesRefundedFees'] = ApiClient.convertToType(data['CashSalesRefundedFees'], 'Number');
            }
            if (data.hasOwnProperty('PosSalesRefundedFees')) {
                obj['PosSalesRefundedFees'] = ApiClient.convertToType(data['PosSalesRefundedFees'], 'Number');
            }
            if (data.hasOwnProperty('SalesFeesVat')) {
                obj['SalesFeesVat'] = ApiClient.convertToType(data['SalesFeesVat'], 'Number');
            }
            if (data.hasOwnProperty('TotalFees')) {
                obj['TotalFees'] = ApiClient.convertToType(data['TotalFees'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Fees on online sales
 * @member {Number} OnlineSalesFees
 */
FlipdishFeesDetails.prototype['OnlineSalesFees'] = undefined;

/**
 * Fees on cash sales
 * @member {Number} CashSalesFees
 */
FlipdishFeesDetails.prototype['CashSalesFees'] = undefined;

/**
 * Fees of POS sales
 * @member {Number} PosSalesFees
 */
FlipdishFeesDetails.prototype['PosSalesFees'] = undefined;

/**
 * Total online and cash sales
 * @member {Number} TotalSalesFees
 */
FlipdishFeesDetails.prototype['TotalSalesFees'] = undefined;

/**
 * Fees on refunds for online sales
 * @member {Number} OnlineSalesRefundedFees
 */
FlipdishFeesDetails.prototype['OnlineSalesRefundedFees'] = undefined;

/**
 * Fees on refunds for cash sales
 * @member {Number} CashSalesRefundedFees
 */
FlipdishFeesDetails.prototype['CashSalesRefundedFees'] = undefined;

/**
 * Fees on refunds for POS sales
 * @member {Number} PosSalesRefundedFees
 */
FlipdishFeesDetails.prototype['PosSalesRefundedFees'] = undefined;

/**
 * VAT on sales fees
 * @member {Number} SalesFeesVat
 */
FlipdishFeesDetails.prototype['SalesFeesVat'] = undefined;

/**
 * Total fees
 * @member {Number} TotalFees
 */
FlipdishFeesDetails.prototype['TotalFees'] = undefined;






export default FlipdishFeesDetails;

