/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GoogleLocation model module.
 * @module model/GoogleLocation
 * @version 1.0.0
 */
class GoogleLocation {
    /**
     * Constructs a new <code>GoogleLocation</code>.
     * @alias module:model/GoogleLocation
     */
    constructor() { 
        
        GoogleLocation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GoogleLocation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GoogleLocation} obj Optional instance to populate.
     * @return {module:model/GoogleLocation} The populated <code>GoogleLocation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GoogleLocation();

            if (data.hasOwnProperty('Lat')) {
                obj['Lat'] = ApiClient.convertToType(data['Lat'], 'Number');
            }
            if (data.hasOwnProperty('Lng')) {
                obj['Lng'] = ApiClient.convertToType(data['Lng'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} Lat
 */
GoogleLocation.prototype['Lat'] = undefined;

/**
 * @member {Number} Lng
 */
GoogleLocation.prototype['Lng'] = undefined;






export default GoogleLocation;

