/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JobDelivery from './JobDelivery';
import JobDriver from './JobDriver';
import JobPricing from './JobPricing';

/**
 * The JobResponse model module.
 * @module model/JobResponse
 * @version 1.0.0
 */
class JobResponse {
    /**
     * Constructs a new <code>JobResponse</code>.
     * Job Response
     * @alias module:model/JobResponse
     */
    constructor() { 
        
        JobResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JobResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobResponse} obj Optional instance to populate.
     * @return {module:model/JobResponse} The populated <code>JobResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobResponse();

            if (data.hasOwnProperty('Id')) {
                obj['Id'] = ApiClient.convertToType(data['Id'], 'Number');
            }
            if (data.hasOwnProperty('CreatedAt')) {
                obj['CreatedAt'] = ApiClient.convertToType(data['CreatedAt'], 'Date');
            }
            if (data.hasOwnProperty('Status')) {
                obj['Status'] = ApiClient.convertToType(data['Status'], 'String');
            }
            if (data.hasOwnProperty('PackageType')) {
                obj['PackageType'] = ApiClient.convertToType(data['PackageType'], 'String');
            }
            if (data.hasOwnProperty('TransportType')) {
                obj['TransportType'] = ApiClient.convertToType(data['TransportType'], 'String');
            }
            if (data.hasOwnProperty('AssignmentCode')) {
                obj['AssignmentCode'] = ApiClient.convertToType(data['AssignmentCode'], 'String');
            }
            if (data.hasOwnProperty('PickupAt')) {
                obj['PickupAt'] = ApiClient.convertToType(data['PickupAt'], 'String');
            }
            if (data.hasOwnProperty('DropoffAt')) {
                obj['DropoffAt'] = ApiClient.convertToType(data['DropoffAt'], 'String');
            }
            if (data.hasOwnProperty('Comment')) {
                obj['Comment'] = ApiClient.convertToType(data['Comment'], 'String');
            }
            if (data.hasOwnProperty('Distance')) {
                obj['Distance'] = ApiClient.convertToType(data['Distance'], 'Number');
            }
            if (data.hasOwnProperty('Duration')) {
                obj['Duration'] = ApiClient.convertToType(data['Duration'], 'Number');
            }
            if (data.hasOwnProperty('Deliveries')) {
                obj['Deliveries'] = ApiClient.convertToType(data['Deliveries'], [JobDelivery]);
            }
            if (data.hasOwnProperty('Pricing')) {
                obj['Pricing'] = JobPricing.constructFromObject(data['Pricing']);
            }
            if (data.hasOwnProperty('Driver')) {
                obj['Driver'] = JobDriver.constructFromObject(data['Driver']);
            }
        }
        return obj;
    }


}

/**
 * Id
 * @member {Number} Id
 */
JobResponse.prototype['Id'] = undefined;

/**
 * Created At
 * @member {Date} CreatedAt
 */
JobResponse.prototype['CreatedAt'] = undefined;

/**
 * Status
 * @member {String} Status
 */
JobResponse.prototype['Status'] = undefined;

/**
 * Package Type
 * @member {String} PackageType
 */
JobResponse.prototype['PackageType'] = undefined;

/**
 * Transport Type
 * @member {String} TransportType
 */
JobResponse.prototype['TransportType'] = undefined;

/**
 * Assignment Code
 * @member {String} AssignmentCode
 */
JobResponse.prototype['AssignmentCode'] = undefined;

/**
 * Pickup At
 * @member {String} PickupAt
 */
JobResponse.prototype['PickupAt'] = undefined;

/**
 * Dropoff At
 * @member {String} DropoffAt
 */
JobResponse.prototype['DropoffAt'] = undefined;

/**
 * Comment
 * @member {String} Comment
 */
JobResponse.prototype['Comment'] = undefined;

/**
 * Distance
 * @member {Number} Distance
 */
JobResponse.prototype['Distance'] = undefined;

/**
 * Duration
 * @member {Number} Duration
 */
JobResponse.prototype['Duration'] = undefined;

/**
 * Deliveries
 * @member {Array.<module:model/JobDelivery>} Deliveries
 */
JobResponse.prototype['Deliveries'] = undefined;

/**
 * @member {module:model/JobPricing} Pricing
 */
JobResponse.prototype['Pricing'] = undefined;

/**
 * @member {module:model/JobDriver} Driver
 */
JobResponse.prototype['Driver'] = undefined;






export default JobResponse;

