/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LoyaltyCampaign from './LoyaltyCampaign';
import UserEventInfo from './UserEventInfo';

/**
 * The LoyaltyCampaignDeletedEvent model module.
 * @module model/LoyaltyCampaignDeletedEvent
 * @version 1.0.0
 */
class LoyaltyCampaignDeletedEvent {
    /**
     * Constructs a new <code>LoyaltyCampaignDeletedEvent</code>.
     * Loyalty campaign deleted event
     * @alias module:model/LoyaltyCampaignDeletedEvent
     */
    constructor() { 
        
        LoyaltyCampaignDeletedEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoyaltyCampaignDeletedEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoyaltyCampaignDeletedEvent} obj Optional instance to populate.
     * @return {module:model/LoyaltyCampaignDeletedEvent} The populated <code>LoyaltyCampaignDeletedEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoyaltyCampaignDeletedEvent();

            if (data.hasOwnProperty('EventName')) {
                obj['EventName'] = ApiClient.convertToType(data['EventName'], 'String');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('StoreId')) {
                obj['StoreId'] = ApiClient.convertToType(data['StoreId'], 'Number');
            }
            if (data.hasOwnProperty('User')) {
                obj['User'] = UserEventInfo.constructFromObject(data['User']);
            }
            if (data.hasOwnProperty('LoyaltyCampaign')) {
                obj['LoyaltyCampaign'] = LoyaltyCampaign.constructFromObject(data['LoyaltyCampaign']);
            }
            if (data.hasOwnProperty('FlipdishEventId')) {
                obj['FlipdishEventId'] = ApiClient.convertToType(data['FlipdishEventId'], 'String');
            }
            if (data.hasOwnProperty('CreateTime')) {
                obj['CreateTime'] = ApiClient.convertToType(data['CreateTime'], 'Date');
            }
            if (data.hasOwnProperty('Position')) {
                obj['Position'] = ApiClient.convertToType(data['Position'], 'Number');
            }
            if (data.hasOwnProperty('AppId')) {
                obj['AppId'] = ApiClient.convertToType(data['AppId'], 'String');
            }
            if (data.hasOwnProperty('IpAddress')) {
                obj['IpAddress'] = ApiClient.convertToType(data['IpAddress'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The event name
 * @member {String} EventName
 */
LoyaltyCampaignDeletedEvent.prototype['EventName'] = undefined;

/**
 * Description
 * @member {String} Description
 */
LoyaltyCampaignDeletedEvent.prototype['Description'] = undefined;

/**
 * Store Id
 * @member {Number} StoreId
 */
LoyaltyCampaignDeletedEvent.prototype['StoreId'] = undefined;

/**
 * @member {module:model/UserEventInfo} User
 */
LoyaltyCampaignDeletedEvent.prototype['User'] = undefined;

/**
 * @member {module:model/LoyaltyCampaign} LoyaltyCampaign
 */
LoyaltyCampaignDeletedEvent.prototype['LoyaltyCampaign'] = undefined;

/**
 * The identitfier of the event
 * @member {String} FlipdishEventId
 */
LoyaltyCampaignDeletedEvent.prototype['FlipdishEventId'] = undefined;

/**
 * The time of creation of the event
 * @member {Date} CreateTime
 */
LoyaltyCampaignDeletedEvent.prototype['CreateTime'] = undefined;

/**
 * Position
 * @member {Number} Position
 */
LoyaltyCampaignDeletedEvent.prototype['Position'] = undefined;

/**
 * App id
 * @member {String} AppId
 */
LoyaltyCampaignDeletedEvent.prototype['AppId'] = undefined;

/**
 * Ip Address
 * @member {String} IpAddress
 */
LoyaltyCampaignDeletedEvent.prototype['IpAddress'] = undefined;






export default LoyaltyCampaignDeletedEvent;

