/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Menu from './Menu';
import UserEventInfo from './UserEventInfo';

/**
 * The MenuUploadedEvent model module.
 * @module model/MenuUploadedEvent
 * @version 1.0.0
 */
class MenuUploadedEvent {
    /**
     * Constructs a new <code>MenuUploadedEvent</code>.
     * Menu uploaded event
     * @alias module:model/MenuUploadedEvent
     */
    constructor() { 
        
        MenuUploadedEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MenuUploadedEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MenuUploadedEvent} obj Optional instance to populate.
     * @return {module:model/MenuUploadedEvent} The populated <code>MenuUploadedEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MenuUploadedEvent();

            if (data.hasOwnProperty('EventName')) {
                obj['EventName'] = ApiClient.convertToType(data['EventName'], 'String');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('User')) {
                obj['User'] = UserEventInfo.constructFromObject(data['User']);
            }
            if (data.hasOwnProperty('Menu')) {
                obj['Menu'] = Menu.constructFromObject(data['Menu']);
            }
            if (data.hasOwnProperty('InstanceEventCount')) {
                obj['InstanceEventCount'] = ApiClient.convertToType(data['InstanceEventCount'], 'String');
            }
            if (data.hasOwnProperty('MenuId')) {
                obj['MenuId'] = ApiClient.convertToType(data['MenuId'], 'Number');
            }
            if (data.hasOwnProperty('FlipdishEventId')) {
                obj['FlipdishEventId'] = ApiClient.convertToType(data['FlipdishEventId'], 'String');
            }
            if (data.hasOwnProperty('CreateTime')) {
                obj['CreateTime'] = ApiClient.convertToType(data['CreateTime'], 'Date');
            }
            if (data.hasOwnProperty('Position')) {
                obj['Position'] = ApiClient.convertToType(data['Position'], 'Number');
            }
            if (data.hasOwnProperty('AppId')) {
                obj['AppId'] = ApiClient.convertToType(data['AppId'], 'String');
            }
            if (data.hasOwnProperty('IpAddress')) {
                obj['IpAddress'] = ApiClient.convertToType(data['IpAddress'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The event name
 * @member {String} EventName
 */
MenuUploadedEvent.prototype['EventName'] = undefined;

/**
 * Description
 * @member {String} Description
 */
MenuUploadedEvent.prototype['Description'] = undefined;

/**
 * @member {module:model/UserEventInfo} User
 */
MenuUploadedEvent.prototype['User'] = undefined;

/**
 * @member {module:model/Menu} Menu
 */
MenuUploadedEvent.prototype['Menu'] = undefined;

/**
 * Quantity of events
 * @member {String} InstanceEventCount
 */
MenuUploadedEvent.prototype['InstanceEventCount'] = undefined;

/**
 * The menu Id
 * @member {Number} MenuId
 */
MenuUploadedEvent.prototype['MenuId'] = undefined;

/**
 * The identitfier of the event
 * @member {String} FlipdishEventId
 */
MenuUploadedEvent.prototype['FlipdishEventId'] = undefined;

/**
 * The time of creation of the event
 * @member {Date} CreateTime
 */
MenuUploadedEvent.prototype['CreateTime'] = undefined;

/**
 * Position
 * @member {Number} Position
 */
MenuUploadedEvent.prototype['Position'] = undefined;

/**
 * App id
 * @member {String} AppId
 */
MenuUploadedEvent.prototype['AppId'] = undefined;

/**
 * Ip Address
 * @member {String} IpAddress
 */
MenuUploadedEvent.prototype['IpAddress'] = undefined;






export default MenuUploadedEvent;

