/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Flipdish) {
      root.Flipdish = {};
    }
    root.Flipdish.MenuElementHide = factory(root.Flipdish.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The MenuElementHide model module.
   * @module model/MenuElementHide
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MenuElementHide</code>.
   * Menu element hide
   * @alias module:model/MenuElementHide
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>MenuElementHide</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MenuElementHide} obj Optional instance to populate.
   * @return {module:model/MenuElementHide} The populated <code>MenuElementHide</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('MenuElementId'))
        obj.MenuElementId = ApiClient.convertToType(data['MenuElementId'], 'Number');
      if (data.hasOwnProperty('MenuElementType'))
        obj.MenuElementType = ApiClient.convertToType(data['MenuElementType'], 'String');
    }
    return obj;
  }

  /**
   * id of the menu item or menu option set item
   * @member {Number} MenuElementId
   */
  exports.prototype.MenuElementId = undefined;

  /**
   * Type of menu element
   * @member {module:model/MenuElementHide.MenuElementTypeEnum} MenuElementType
   */
  exports.prototype.MenuElementType = undefined;



  /**
   * Allowed values for the <code>MenuElementType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.MenuElementTypeEnum = {
    /**
     * value: "MenuItem"
     * @const
     */
    MenuItem: "MenuItem",

    /**
     * value: "MenuOptionSetItem"
     * @const
     */
    MenuOptionSetItem: "MenuOptionSetItem"
  };

  return exports;

}));
