/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderFulfillmentStatusUpdatedEvent model module.
 * @module model/OrderFulfillmentStatusUpdatedEvent
 * @version 1.0.0
 */
class OrderFulfillmentStatusUpdatedEvent {
    /**
     * Constructs a new <code>OrderFulfillmentStatusUpdatedEvent</code>.
     * Fulfillment status updated event
     * @alias module:model/OrderFulfillmentStatusUpdatedEvent
     */
    constructor() { 
        
        OrderFulfillmentStatusUpdatedEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OrderFulfillmentStatusUpdatedEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderFulfillmentStatusUpdatedEvent} obj Optional instance to populate.
     * @return {module:model/OrderFulfillmentStatusUpdatedEvent} The populated <code>OrderFulfillmentStatusUpdatedEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderFulfillmentStatusUpdatedEvent();

            if (data.hasOwnProperty('EventName')) {
                obj['EventName'] = ApiClient.convertToType(data['EventName'], 'String');
            }
            if (data.hasOwnProperty('StoreId')) {
                obj['StoreId'] = ApiClient.convertToType(data['StoreId'], 'Number');
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('OrderId')) {
                obj['OrderId'] = ApiClient.convertToType(data['OrderId'], 'Number');
            }
            if (data.hasOwnProperty('StatusName')) {
                obj['StatusName'] = ApiClient.convertToType(data['StatusName'], 'String');
            }
            if (data.hasOwnProperty('StatusId')) {
                obj['StatusId'] = ApiClient.convertToType(data['StatusId'], 'String');
            }
            if (data.hasOwnProperty('FlipdishEventId')) {
                obj['FlipdishEventId'] = ApiClient.convertToType(data['FlipdishEventId'], 'String');
            }
            if (data.hasOwnProperty('CreateTime')) {
                obj['CreateTime'] = ApiClient.convertToType(data['CreateTime'], 'Date');
            }
            if (data.hasOwnProperty('Position')) {
                obj['Position'] = ApiClient.convertToType(data['Position'], 'Number');
            }
            if (data.hasOwnProperty('AppId')) {
                obj['AppId'] = ApiClient.convertToType(data['AppId'], 'String');
            }
            if (data.hasOwnProperty('OrgId')) {
                obj['OrgId'] = ApiClient.convertToType(data['OrgId'], 'String');
            }
            if (data.hasOwnProperty('IpAddress')) {
                obj['IpAddress'] = ApiClient.convertToType(data['IpAddress'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The event name
 * @member {String} EventName
 */
OrderFulfillmentStatusUpdatedEvent.prototype['EventName'] = undefined;

/**
 * Store Id
 * @member {Number} StoreId
 */
OrderFulfillmentStatusUpdatedEvent.prototype['StoreId'] = undefined;

/**
 * Description
 * @member {String} Description
 */
OrderFulfillmentStatusUpdatedEvent.prototype['Description'] = undefined;

/**
 * Order Id
 * @member {Number} OrderId
 */
OrderFulfillmentStatusUpdatedEvent.prototype['OrderId'] = undefined;

/**
 * Fulfillment status name
 * @member {String} StatusName
 */
OrderFulfillmentStatusUpdatedEvent.prototype['StatusName'] = undefined;

/**
 * Fulfillment status ID
 * @member {String} StatusId
 */
OrderFulfillmentStatusUpdatedEvent.prototype['StatusId'] = undefined;

/**
 * The identitfier of the event
 * @member {String} FlipdishEventId
 */
OrderFulfillmentStatusUpdatedEvent.prototype['FlipdishEventId'] = undefined;

/**
 * The time of creation of the event
 * @member {Date} CreateTime
 */
OrderFulfillmentStatusUpdatedEvent.prototype['CreateTime'] = undefined;

/**
 * Position
 * @member {Number} Position
 */
OrderFulfillmentStatusUpdatedEvent.prototype['Position'] = undefined;

/**
 * App id
 * @member {String} AppId
 */
OrderFulfillmentStatusUpdatedEvent.prototype['AppId'] = undefined;

/**
 * Org id
 * @member {String} OrgId
 */
OrderFulfillmentStatusUpdatedEvent.prototype['OrgId'] = undefined;

/**
 * Ip Address
 * @member {String} IpAddress
 */
OrderFulfillmentStatusUpdatedEvent.prototype['IpAddress'] = undefined;






export default OrderFulfillmentStatusUpdatedEvent;

