/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.FlipdishOpenApiV10) {
      root.FlipdishOpenApiV10 = {};
    }
    root.FlipdishOpenApiV10.PaymentTerminalTransactionDetails = factory(root.FlipdishOpenApiV10.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PaymentTerminalTransactionDetails model module.
   * @module model/PaymentTerminalTransactionDetails
   * @version v1.0
   */

  /**
   * Constructs a new <code>PaymentTerminalTransactionDetails</code>.
   * Details of Payment Terminal Transaction
   * @alias module:model/PaymentTerminalTransactionDetails
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PaymentTerminalTransactionDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentTerminalTransactionDetails} obj Optional instance to populate.
   * @return {module:model/PaymentTerminalTransactionDetails} The populated <code>PaymentTerminalTransactionDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('CardSchemeName'))
        obj.cardSchemeName = ApiClient.convertToType(data['CardSchemeName'], 'String');
      if (data.hasOwnProperty('DateOfExpiry'))
        obj.dateOfExpiry = ApiClient.convertToType(data['DateOfExpiry'], 'String');
      if (data.hasOwnProperty('AuthCode'))
        obj.authCode = ApiClient.convertToType(data['AuthCode'], 'String');
      if (data.hasOwnProperty('TransactionResult'))
        obj.transactionResult = ApiClient.convertToType(data['TransactionResult'], 'String');
      if (data.hasOwnProperty('PrimaryAccountNumber'))
        obj.primaryAccountNumber = ApiClient.convertToType(data['PrimaryAccountNumber'], 'String');
      if (data.hasOwnProperty('CardholderVerificationMethod'))
        obj.cardholderVerificationMethod = ApiClient.convertToType(data['CardholderVerificationMethod'], 'String');
    }
    return obj;
  }

  /**
   * Card Type
   * @member {String} cardSchemeName
   */
  exports.prototype.cardSchemeName = undefined;

  /**
   * Expirey Date on Card
   * @member {String} dateOfExpiry
   */
  exports.prototype.dateOfExpiry = undefined;

  /**
   * AuthCode
   * @member {String} authCode
   */
  exports.prototype.authCode = undefined;

  /**
   * State of Request, \"PENDING\" is not yet completed
   * @member {String} transactionResult
   */
  exports.prototype.transactionResult = undefined;

  /**
   * Masked PAN
   * @member {String} primaryAccountNumber
   */
  exports.prototype.primaryAccountNumber = undefined;

  /**
   * Type of Verification.
   * @member {String} cardholderVerificationMethod
   */
  exports.prototype.cardholderVerificationMethod = undefined;


  return exports;

}));
