/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayoutReport3Details from './PayoutReport3Details';
import PayoutReport3PropertyFilterOption from './PayoutReport3PropertyFilterOption';

/**
 * The PayoutReport3PropertyDetails model module.
 * @module model/PayoutReport3PropertyDetails
 * @version 1.0.0
 */
class PayoutReport3PropertyDetails {
    /**
     * Constructs a new <code>PayoutReport3PropertyDetails</code>.
     * @alias module:model/PayoutReport3PropertyDetails
     */
    constructor() { 
        
        PayoutReport3PropertyDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PayoutReport3PropertyDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayoutReport3PropertyDetails} obj Optional instance to populate.
     * @return {module:model/PayoutReport3PropertyDetails} The populated <code>PayoutReport3PropertyDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayoutReport3PropertyDetails();

            if (data.hasOwnProperty('AvailableProperties')) {
                obj['AvailableProperties'] = ApiClient.convertToType(data['AvailableProperties'], [PayoutReport3PropertyFilterOption]);
            }
            if (data.hasOwnProperty('SelectedPropertyIds')) {
                obj['SelectedPropertyIds'] = ApiClient.convertToType(data['SelectedPropertyIds'], ['String']);
            }
            if (data.hasOwnProperty('MatchedStoreIds')) {
                obj['MatchedStoreIds'] = ApiClient.convertToType(data['MatchedStoreIds'], ['Number']);
            }
            if (data.hasOwnProperty('Details')) {
                obj['Details'] = PayoutReport3Details.constructFromObject(data['Details']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/PayoutReport3PropertyFilterOption>} AvailableProperties
 */
PayoutReport3PropertyDetails.prototype['AvailableProperties'] = undefined;

/**
 * @member {Array.<String>} SelectedPropertyIds
 */
PayoutReport3PropertyDetails.prototype['SelectedPropertyIds'] = undefined;

/**
 * @member {Array.<Number>} MatchedStoreIds
 */
PayoutReport3PropertyDetails.prototype['MatchedStoreIds'] = undefined;

/**
 * @member {module:model/PayoutReport3Details} Details
 */
PayoutReport3PropertyDetails.prototype['Details'] = undefined;






export default PayoutReport3PropertyDetails;

