/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Flipdish) {
      root.Flipdish = {};
    }
    root.Flipdish.PosRevenueDetails = factory(root.Flipdish.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PosRevenueDetails model module.
   * @module model/PosRevenueDetails
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PosRevenueDetails</code>.
   * Breakdown of POS charges
   * @alias module:model/PosRevenueDetails
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>PosRevenueDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PosRevenueDetails} obj Optional instance to populate.
   * @return {module:model/PosRevenueDetails} The populated <code>PosRevenueDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('PosSalesAmount'))
        obj.PosSalesAmount = ApiClient.convertToType(data['PosSalesAmount'], 'Number');
      if (data.hasOwnProperty('PosSalesTax'))
        obj.PosSalesTax = ApiClient.convertToType(data['PosSalesTax'], 'Number');
      if (data.hasOwnProperty('PosSalesTips'))
        obj.PosSalesTips = ApiClient.convertToType(data['PosSalesTips'], 'Number');
      if (data.hasOwnProperty('TotalPosRevenue'))
        obj.TotalPosRevenue = ApiClient.convertToType(data['TotalPosRevenue'], 'Number');
    }
    return obj;
  }

  /**
   * POS sale amount for the store
   * @member {Number} PosSalesAmount
   */
  exports.prototype.PosSalesAmount = undefined;

  /**
   * POS sale Tax for the store
   * @member {Number} PosSalesTax
   */
  exports.prototype.PosSalesTax = undefined;

  /**
   * POS sale tips for the store
   * @member {Number} PosSalesTips
   */
  exports.prototype.PosSalesTips = undefined;

  /**
   * POS Total Revenue for the store
   * @member {Number} TotalPosRevenue
   */
  exports.prototype.TotalPosRevenue = undefined;


  return exports;

}));
