/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Flipdish) {
      root.Flipdish = {};
    }
    root.Flipdish.PushNotificationResponse = factory(root.Flipdish.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The PushNotificationResponse model module.
   * @module model/PushNotificationResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>PushNotificationResponse</code>.
   * Push Notification
   * @alias module:model/PushNotificationResponse
   * @class
   * @param Message {String} Message of the notification
   */
  var exports = function(Message) {
    this.Message = Message;
  };

  /**
   * Constructs a <code>PushNotificationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PushNotificationResponse} obj Optional instance to populate.
   * @return {module:model/PushNotificationResponse} The populated <code>PushNotificationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Sent'))
        obj.Sent = ApiClient.convertToType(data['Sent'], 'Boolean');
      if (data.hasOwnProperty('ScheduledPushNotificationId'))
        obj.ScheduledPushNotificationId = ApiClient.convertToType(data['ScheduledPushNotificationId'], 'Number');
      if (data.hasOwnProperty('ScheduledTime'))
        obj.ScheduledTime = ApiClient.convertToType(data['ScheduledTime'], 'Date');
      if (data.hasOwnProperty('Title'))
        obj.Title = ApiClient.convertToType(data['Title'], 'String');
      if (data.hasOwnProperty('Message'))
        obj.Message = ApiClient.convertToType(data['Message'], 'String');
    }
    return obj;
  }

  /**
   * Sent
   * @member {Boolean} Sent
   */
  exports.prototype.Sent = undefined;

  /**
   * Push notification identifier
   * @member {Number} ScheduledPushNotificationId
   */
  exports.prototype.ScheduledPushNotificationId = undefined;

  /**
   * UTC Time at which to send the push notification
   * @member {Date} ScheduledTime
   */
  exports.prototype.ScheduledTime = undefined;

  /**
   * Title of the notification
   * @member {String} Title
   */
  exports.prototype.Title = undefined;

  /**
   * Message of the notification
   * @member {String} Message
   */
  exports.prototype.Message = undefined;


  return exports;

}));
