/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RetentionCampaign from './RetentionCampaign';

/**
 * The RestApiArrayResultRetentionCampaign model module.
 * @module model/RestApiArrayResultRetentionCampaign
 * @version 1.0.0
 */
class RestApiArrayResultRetentionCampaign {
    /**
     * Constructs a new <code>RestApiArrayResultRetentionCampaign</code>.
     * Rest api array result
     * @alias module:model/RestApiArrayResultRetentionCampaign
     * @param Data {Array.<module:model/RetentionCampaign>} Generic data object.
     */
    constructor(Data) { 
        
        RestApiArrayResultRetentionCampaign.initialize(this, Data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, Data) { 
        obj['Data'] = Data;
    }

    /**
     * Constructs a <code>RestApiArrayResultRetentionCampaign</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestApiArrayResultRetentionCampaign} obj Optional instance to populate.
     * @return {module:model/RestApiArrayResultRetentionCampaign} The populated <code>RestApiArrayResultRetentionCampaign</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestApiArrayResultRetentionCampaign();

            if (data.hasOwnProperty('Data')) {
                obj['Data'] = ApiClient.convertToType(data['Data'], [RetentionCampaign]);
            }
        }
        return obj;
    }


}

/**
 * Generic data object.
 * @member {Array.<module:model/RetentionCampaign>} Data
 */
RestApiArrayResultRetentionCampaign.prototype['Data'] = undefined;






export default RestApiArrayResultRetentionCampaign;

