/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Voucher from './Voucher';

/**
 * The RestApiResultVoucher model module.
 * @module model/RestApiResultVoucher
 * @version 1.0.0
 */
class RestApiResultVoucher {
    /**
     * Constructs a new <code>RestApiResultVoucher</code>.
     * Rest api result
     * @alias module:model/RestApiResultVoucher
     * @param Data {module:model/Voucher} 
     */
    constructor(Data) { 
        
        RestApiResultVoucher.initialize(this, Data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, Data) { 
        obj['Data'] = Data;
    }

    /**
     * Constructs a <code>RestApiResultVoucher</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestApiResultVoucher} obj Optional instance to populate.
     * @return {module:model/RestApiResultVoucher} The populated <code>RestApiResultVoucher</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestApiResultVoucher();

            if (data.hasOwnProperty('Data')) {
                obj['Data'] = Voucher.constructFromObject(data['Data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Voucher} Data
 */
RestApiResultVoucher.prototype['Data'] = undefined;






export default RestApiResultVoucher;

