/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AppStoreConfigModel from './AppStoreConfigModel';

/**
 * The RestApiResultAppStoreConfigModel model module.
 * @module model/RestApiResultAppStoreConfigModel
 * @version 1.0.0
 */
class RestApiResultAppStoreConfigModel {
    /**
     * Constructs a new <code>RestApiResultAppStoreConfigModel</code>.
     * Rest api result
     * @alias module:model/RestApiResultAppStoreConfigModel
     * @param Data {module:model/AppStoreConfigModel} 
     */
    constructor(Data) { 
        
        RestApiResultAppStoreConfigModel.initialize(this, Data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, Data) { 
        obj['Data'] = Data;
    }

    /**
     * Constructs a <code>RestApiResultAppStoreConfigModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestApiResultAppStoreConfigModel} obj Optional instance to populate.
     * @return {module:model/RestApiResultAppStoreConfigModel} The populated <code>RestApiResultAppStoreConfigModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestApiResultAppStoreConfigModel();

            if (data.hasOwnProperty('Data')) {
                obj['Data'] = AppStoreConfigModel.constructFromObject(data['Data']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AppStoreConfigModel} Data
 */
RestApiResultAppStoreConfigModel.prototype['Data'] = undefined;






export default RestApiResultAppStoreConfigModel;

