/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RestApiForbiddenResult model module.
 * @module model/RestApiForbiddenResult
 * @version 1.0.0
 */
class RestApiForbiddenResult {
    /**
     * Constructs a new <code>RestApiForbiddenResult</code>.
     * Rest Api Forbidden Result
     * @alias module:model/RestApiForbiddenResult
     * @param Message {String} Message
     */
    constructor(Message) { 
        
        RestApiForbiddenResult.initialize(this, Message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, Message) { 
        obj['Message'] = Message;
    }

    /**
     * Constructs a <code>RestApiForbiddenResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestApiForbiddenResult} obj Optional instance to populate.
     * @return {module:model/RestApiForbiddenResult} The populated <code>RestApiForbiddenResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestApiForbiddenResult();

            if (data.hasOwnProperty('Message')) {
                obj['Message'] = ApiClient.convertToType(data['Message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Message
 * @member {String} Message
 */
RestApiForbiddenResult.prototype['Message'] = undefined;






export default RestApiForbiddenResult;

