/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RestaurantVoucherAssignedStore from './RestaurantVoucherAssignedStore';

/**
 * The RestaurantVoucherPayGreenConfiguration model module.
 * @module model/RestaurantVoucherPayGreenConfiguration
 * @version 1.0.0
 */
class RestaurantVoucherPayGreenConfiguration {
    /**
     * Constructs a new <code>RestaurantVoucherPayGreenConfiguration</code>.
     * @alias module:model/RestaurantVoucherPayGreenConfiguration
     */
    constructor() { 
        
        RestaurantVoucherPayGreenConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RestaurantVoucherPayGreenConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RestaurantVoucherPayGreenConfiguration} obj Optional instance to populate.
     * @return {module:model/RestaurantVoucherPayGreenConfiguration} The populated <code>RestaurantVoucherPayGreenConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RestaurantVoucherPayGreenConfiguration();

            if (data.hasOwnProperty('Name')) {
                obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
            }
            if (data.hasOwnProperty('PayGreenId')) {
                obj['PayGreenId'] = ApiClient.convertToType(data['PayGreenId'], 'String');
            }
            if (data.hasOwnProperty('PayGreenConfigurationId')) {
                obj['PayGreenConfigurationId'] = ApiClient.convertToType(data['PayGreenConfigurationId'], 'Number');
            }
            if (data.hasOwnProperty('AssignedStores')) {
                obj['AssignedStores'] = ApiClient.convertToType(data['AssignedStores'], [RestaurantVoucherAssignedStore]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} Name
 */
RestaurantVoucherPayGreenConfiguration.prototype['Name'] = undefined;

/**
 * @member {String} PayGreenId
 */
RestaurantVoucherPayGreenConfiguration.prototype['PayGreenId'] = undefined;

/**
 * @member {Number} PayGreenConfigurationId
 */
RestaurantVoucherPayGreenConfiguration.prototype['PayGreenConfigurationId'] = undefined;

/**
 * @member {Array.<module:model/RestaurantVoucherAssignedStore>} AssignedStores
 */
RestaurantVoucherPayGreenConfiguration.prototype['AssignedStores'] = undefined;






export default RestaurantVoucherPayGreenConfiguration;

