/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetV2FeeCalculationRequest model module.
 * @module model/SetV2FeeCalculationRequest
 * @version 1.0.0
 */
class SetV2FeeCalculationRequest {
    /**
     * Constructs a new <code>SetV2FeeCalculationRequest</code>.
     * Input model for setting whether the V2 (tiered) fee calculation is enabled for a Store
     * @alias module:model/SetV2FeeCalculationRequest
     */
    constructor() { 
        
        SetV2FeeCalculationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetV2FeeCalculationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetV2FeeCalculationRequest} obj Optional instance to populate.
     * @return {module:model/SetV2FeeCalculationRequest} The populated <code>SetV2FeeCalculationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetV2FeeCalculationRequest();

            if (data.hasOwnProperty('IsEnabled')) {
                obj['IsEnabled'] = ApiClient.convertToType(data['IsEnabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Whether the V2 (tiered) fee calculation should be enabled for this Store. Required.
 * @member {Boolean} IsEnabled
 */
SetV2FeeCalculationRequest.prototype['IsEnabled'] = undefined;






export default SetV2FeeCalculationRequest;

