/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Coordinates from './Coordinates';

/**
 * The StoreAddress model module.
 * @module model/StoreAddress
 * @version 1.0.0
 */
class StoreAddress {
    /**
     * Constructs a new <code>StoreAddress</code>.
     * Store address
     * @alias module:model/StoreAddress
     */
    constructor() { 
        
        StoreAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoreAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreAddress} obj Optional instance to populate.
     * @return {module:model/StoreAddress} The populated <code>StoreAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreAddress();

            if (data.hasOwnProperty('AddressId')) {
                obj['AddressId'] = ApiClient.convertToType(data['AddressId'], 'Number');
            }
            if (data.hasOwnProperty('Coordinates')) {
                obj['Coordinates'] = Coordinates.constructFromObject(data['Coordinates']);
            }
            if (data.hasOwnProperty('Line1')) {
                obj['Line1'] = ApiClient.convertToType(data['Line1'], 'String');
            }
            if (data.hasOwnProperty('Postcode')) {
                obj['Postcode'] = ApiClient.convertToType(data['Postcode'], 'String');
            }
            if (data.hasOwnProperty('City')) {
                obj['City'] = ApiClient.convertToType(data['City'], 'String');
            }
            if (data.hasOwnProperty('CountryCode')) {
                obj['CountryCode'] = ApiClient.convertToType(data['CountryCode'], 'String');
            }
            if (data.hasOwnProperty('DisplayForCustomer')) {
                obj['DisplayForCustomer'] = ApiClient.convertToType(data['DisplayForCustomer'], 'String');
            }
            if (data.hasOwnProperty('AddressFields')) {
                obj['AddressFields'] = ApiClient.convertToType(data['AddressFields'], {'String': Object});
            }
            if (data.hasOwnProperty('SingleLineDisplay')) {
                obj['SingleLineDisplay'] = ApiClient.convertToType(data['SingleLineDisplay'], 'String');
            }
            if (data.hasOwnProperty('TwoLinesDisplay')) {
                obj['TwoLinesDisplay'] = ApiClient.convertToType(data['TwoLinesDisplay'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * Address identifier
 * @member {Number} AddressId
 */
StoreAddress.prototype['AddressId'] = undefined;

/**
 * @member {module:model/Coordinates} Coordinates
 */
StoreAddress.prototype['Coordinates'] = undefined;

/**
 * Address line 1
 * @member {String} Line1
 */
StoreAddress.prototype['Line1'] = undefined;

/**
 * Postcode
 * @member {String} Postcode
 */
StoreAddress.prototype['Postcode'] = undefined;

/**
 * City
 * @member {String} City
 */
StoreAddress.prototype['City'] = undefined;

/**
 * Country code (ISO-alpha2)
 * @member {String} CountryCode
 */
StoreAddress.prototype['CountryCode'] = undefined;

/**
 * Display for customer
 * @member {String} DisplayForCustomer
 */
StoreAddress.prototype['DisplayForCustomer'] = undefined;

/**
 * Dyanmic field/value pairs, defined by the form assigned to the given country code.
 * @member {Object.<String, Object>} AddressFields
 */
StoreAddress.prototype['AddressFields'] = undefined;

/**
 * Single line display i18n, may be empty for not supported countries
 * @member {String} SingleLineDisplay
 */
StoreAddress.prototype['SingleLineDisplay'] = undefined;

/**
 * Two line display i18n, may be empty for not supported countries
 * @member {Array.<String>} TwoLinesDisplay
 */
StoreAddress.prototype['TwoLinesDisplay'] = undefined;






export default StoreAddress;

