/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StoreGroup from './StoreGroup';
import UserEventInfo from './UserEventInfo';

/**
 * The StoreGroupDeletedEvent model module.
 * @module model/StoreGroupDeletedEvent
 * @version 1.0.0
 */
class StoreGroupDeletedEvent {
    /**
     * Constructs a new <code>StoreGroupDeletedEvent</code>.
     * Store Group Deleted Event
     * @alias module:model/StoreGroupDeletedEvent
     */
    constructor() { 
        
        StoreGroupDeletedEvent.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StoreGroupDeletedEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StoreGroupDeletedEvent} obj Optional instance to populate.
     * @return {module:model/StoreGroupDeletedEvent} The populated <code>StoreGroupDeletedEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StoreGroupDeletedEvent();

            if (data.hasOwnProperty('EventName')) {
                obj['EventName'] = ApiClient.convertToType(data['EventName'], 'String');
            }
            if (data.hasOwnProperty('StoreGroupId')) {
                obj['StoreGroupId'] = ApiClient.convertToType(data['StoreGroupId'], 'Number');
            }
            if (data.hasOwnProperty('User')) {
                obj['User'] = UserEventInfo.constructFromObject(data['User']);
            }
            if (data.hasOwnProperty('Description')) {
                obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
            }
            if (data.hasOwnProperty('StoreGroup')) {
                obj['StoreGroup'] = StoreGroup.constructFromObject(data['StoreGroup']);
            }
            if (data.hasOwnProperty('FlipdishEventId')) {
                obj['FlipdishEventId'] = ApiClient.convertToType(data['FlipdishEventId'], 'String');
            }
            if (data.hasOwnProperty('CreateTime')) {
                obj['CreateTime'] = ApiClient.convertToType(data['CreateTime'], 'Date');
            }
            if (data.hasOwnProperty('Position')) {
                obj['Position'] = ApiClient.convertToType(data['Position'], 'Number');
            }
            if (data.hasOwnProperty('AppId')) {
                obj['AppId'] = ApiClient.convertToType(data['AppId'], 'String');
            }
            if (data.hasOwnProperty('IpAddress')) {
                obj['IpAddress'] = ApiClient.convertToType(data['IpAddress'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The event name
 * @member {String} EventName
 */
StoreGroupDeletedEvent.prototype['EventName'] = undefined;

/**
 * Store Group Id
 * @member {Number} StoreGroupId
 */
StoreGroupDeletedEvent.prototype['StoreGroupId'] = undefined;

/**
 * @member {module:model/UserEventInfo} User
 */
StoreGroupDeletedEvent.prototype['User'] = undefined;

/**
 * Description
 * @member {String} Description
 */
StoreGroupDeletedEvent.prototype['Description'] = undefined;

/**
 * @member {module:model/StoreGroup} StoreGroup
 */
StoreGroupDeletedEvent.prototype['StoreGroup'] = undefined;

/**
 * The identitfier of the event
 * @member {String} FlipdishEventId
 */
StoreGroupDeletedEvent.prototype['FlipdishEventId'] = undefined;

/**
 * The time of creation of the event
 * @member {Date} CreateTime
 */
StoreGroupDeletedEvent.prototype['CreateTime'] = undefined;

/**
 * Position
 * @member {Number} Position
 */
StoreGroupDeletedEvent.prototype['Position'] = undefined;

/**
 * App id
 * @member {String} AppId
 */
StoreGroupDeletedEvent.prototype['AppId'] = undefined;

/**
 * Ip Address
 * @member {String} IpAddress
 */
StoreGroupDeletedEvent.prototype['IpAddress'] = undefined;






export default StoreGroupDeletedEvent;

