version: 2

defaults: &defaults
  working_directory: ~/api-client-javascript
  docker:
    - image: cimg/node:22.7.0
jobs:
  deploy:
    <<: *defaults
    steps:
        - checkout
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run: npm install
        - run: npm prune
        - run:
            name: Versioning
            command: npm version 1.0.$CIRCLE_BUILD_NUM --no-git-tag-version
        - run:
            name: Version
            command: npm version
        - run:
            name: Publish package
            command: npm publish --access public
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: /^master/
