/*
 * Flipdish Open API v1.0
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.43
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ExternalStoreAuditLog', 'model/RestApiErrorResult', 'model/RestApiForbiddenResult', 'model/RestApiUnauthorizedResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ExternalStoreAuditLog'), require('../model/RestApiErrorResult'), require('../model/RestApiForbiddenResult'), require('../model/RestApiUnauthorizedResult'));
  } else {
    // Browser globals (root is window)
    if (!root.Flipdish) {
      root.Flipdish = {};
    }
    root.Flipdish.AuditLogsApi = factory(root.Flipdish.ApiClient, root.Flipdish.ExternalStoreAuditLog, root.Flipdish.RestApiErrorResult, root.Flipdish.RestApiForbiddenResult, root.Flipdish.RestApiUnauthorizedResult);
  }
}(this, function(ApiClient, ExternalStoreAuditLog, RestApiErrorResult, RestApiForbiddenResult, RestApiUnauthorizedResult) {
  'use strict';

  /**
   * AuditLogs service.
   * @module api/AuditLogsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AuditLogsApi. 
   * @alias module:api/AuditLogsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addOrderAuditLog operation.
     * @callback module:api/AuditLogsApi~addOrderAuditLogCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} orderId 
     * @param {Array.<module:model/ExternalStoreAuditLog>} externalEventCreate 
     * @param {module:api/AuditLogsApi~addOrderAuditLogCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addOrderAuditLog = function(orderId, externalEventCreate, callback) {
      var postBody = externalEventCreate;

      // verify the required parameter 'orderId' is set
      if (orderId === undefined || orderId === null) {
        throw new Error("Missing the required parameter 'orderId' when calling addOrderAuditLog");
      }

      // verify the required parameter 'externalEventCreate' is set
      if (externalEventCreate === undefined || externalEventCreate === null) {
        throw new Error("Missing the required parameter 'externalEventCreate' when calling addOrderAuditLog");
      }


      var pathParams = {
        'orderId': orderId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2'];
      var contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1.0/auditlogs/orders/{orderId}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the addStoreAuditLogEvent operation.
     * @callback module:api/AuditLogsApi~addStoreAuditLogEventCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} storeId 
     * @param {Array.<module:model/ExternalStoreAuditLog>} externalEventCreate 
     * @param {module:api/AuditLogsApi~addStoreAuditLogEventCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.addStoreAuditLogEvent = function(storeId, externalEventCreate, callback) {
      var postBody = externalEventCreate;

      // verify the required parameter 'storeId' is set
      if (storeId === undefined || storeId === null) {
        throw new Error("Missing the required parameter 'storeId' when calling addStoreAuditLogEvent");
      }

      // verify the required parameter 'externalEventCreate' is set
      if (externalEventCreate === undefined || externalEventCreate === null) {
        throw new Error("Missing the required parameter 'externalEventCreate' when calling addStoreAuditLogEvent");
      }


      var pathParams = {
        'storeId': storeId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['oauth2'];
      var contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      var accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1.0/auditlogs/stores/{storeId}', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
