/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RestApiErrorResult from '../model/RestApiErrorResult';
import RestApiForbiddenResult from '../model/RestApiForbiddenResult';
import RestApiResultJobResponse from '../model/RestApiResultJobResponse';
import RestApiResultStuartSettings from '../model/RestApiResultStuartSettings';
import RestApiUnauthorizedResult from '../model/RestApiUnauthorizedResult';
import StuartSettings from '../model/StuartSettings';

/**
* Stuart service.
* @module api/StuartApi
* @version 1.0.0
*/
export default class StuartApi {

    /**
    * Constructs a new StuartApi. 
    * @alias module:api/StuartApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the stuartCancelJob operation.
     * @callback module:api/StuartApi~stuartCancelJobCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} jobId 
     * @param {Number} storeId 
     * @param {module:api/StuartApi~stuartCancelJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    stuartCancelJob(jobId, storeId, callback) {
      let postBody = null;
      // verify the required parameter 'jobId' is set
      if (jobId === undefined || jobId === null) {
        throw new Error("Missing the required parameter 'jobId' when calling stuartCancelJob");
      }
      // verify the required parameter 'storeId' is set
      if (storeId === undefined || storeId === null) {
        throw new Error("Missing the required parameter 'storeId' when calling stuartCancelJob");
      }

      let pathParams = {
        'jobId': jobId
      };
      let queryParams = {
        'storeId': storeId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1.0/stuart/jobs/{jobId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the stuartGetJob operation.
     * @callback module:api/StuartApi~stuartGetJobCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RestApiResultJobResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} jobId 
     * @param {Number} storeId 
     * @param {module:api/StuartApi~stuartGetJobCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RestApiResultJobResponse}
     */
    stuartGetJob(jobId, storeId, callback) {
      let postBody = null;
      // verify the required parameter 'jobId' is set
      if (jobId === undefined || jobId === null) {
        throw new Error("Missing the required parameter 'jobId' when calling stuartGetJob");
      }
      // verify the required parameter 'storeId' is set
      if (storeId === undefined || storeId === null) {
        throw new Error("Missing the required parameter 'storeId' when calling stuartGetJob");
      }

      let pathParams = {
        'jobId': jobId
      };
      let queryParams = {
        'storeId': storeId
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml', 'Data'];
      let returnType = RestApiResultJobResponse;
      return this.apiClient.callApi(
        '/api/v1.0/stuart/jobs/{jobId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the stuartGetStuartSettings operation.
     * @callback module:api/StuartApi~stuartGetStuartSettingsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RestApiResultStuartSettings} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} storeId 
     * @param {module:api/StuartApi~stuartGetStuartSettingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RestApiResultStuartSettings}
     */
    stuartGetStuartSettings(storeId, callback) {
      let postBody = null;
      // verify the required parameter 'storeId' is set
      if (storeId === undefined || storeId === null) {
        throw new Error("Missing the required parameter 'storeId' when calling stuartGetStuartSettings");
      }

      let pathParams = {
        'storeId': storeId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml', 'Data'];
      let returnType = RestApiResultStuartSettings;
      return this.apiClient.callApi(
        '/api/v1.0/stuart/settings/{storeId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the stuartPostStuartSettings operation.
     * @callback module:api/StuartApi~stuartPostStuartSettingsCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} storeId 
     * @param {module:model/StuartSettings} stuartSettings 
     * @param {module:api/StuartApi~stuartPostStuartSettingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    stuartPostStuartSettings(storeId, stuartSettings, callback) {
      let postBody = stuartSettings;
      // verify the required parameter 'storeId' is set
      if (storeId === undefined || storeId === null) {
        throw new Error("Missing the required parameter 'storeId' when calling stuartPostStuartSettings");
      }
      // verify the required parameter 'stuartSettings' is set
      if (stuartSettings === undefined || stuartSettings === null) {
        throw new Error("Missing the required parameter 'stuartSettings' when calling stuartPostStuartSettings");
      }

      let pathParams = {
        'storeId': storeId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml', 'Data'];
      let returnType = Object;
      return this.apiClient.callApi(
        '/api/v1.0/stuart/settings/{storeId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
