/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import RestApiErrorResult from '../model/RestApiErrorResult';
import RestApiForbiddenResult from '../model/RestApiForbiddenResult';
import RestApiResultTipConfiguration from '../model/RestApiResultTipConfiguration';
import RestApiUnauthorizedResult from '../model/RestApiUnauthorizedResult';
import UpdateTipConfiguration from '../model/UpdateTipConfiguration';

/**
* Tips service.
* @module api/TipsApi
* @version 1.0.0
*/
export default class TipsApi {

    /**
    * Constructs a new TipsApi. 
    * @alias module:api/TipsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the tipConfigGet operation.
     * @callback module:api/TipsApi~tipConfigGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RestApiResultTipConfiguration} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} storeId 
     * @param {module:api/TipsApi~tipConfigGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RestApiResultTipConfiguration}
     */
    tipConfigGet(storeId, callback) {
      let postBody = null;
      // verify the required parameter 'storeId' is set
      if (storeId === undefined || storeId === null) {
        throw new Error("Missing the required parameter 'storeId' when calling tipConfigGet");
      }

      let pathParams = {
        'storeId': storeId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = [];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml', 'Data', 'Message', 'ErrorCode', 'StackTrace'];
      let returnType = RestApiResultTipConfiguration;
      return this.apiClient.callApi(
        '/api/v1.0/stores/{storeId}/tipconfig', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the tipConfigUpsert operation.
     * @callback module:api/TipsApi~tipConfigUpsertCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RestApiResultTipConfiguration} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} storeId 
     * @param {module:model/UpdateTipConfiguration} updateConfig 
     * @param {module:api/TipsApi~tipConfigUpsertCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RestApiResultTipConfiguration}
     */
    tipConfigUpsert(storeId, updateConfig, callback) {
      let postBody = updateConfig;
      // verify the required parameter 'storeId' is set
      if (storeId === undefined || storeId === null) {
        throw new Error("Missing the required parameter 'storeId' when calling tipConfigUpsert");
      }
      // verify the required parameter 'updateConfig' is set
      if (updateConfig === undefined || updateConfig === null) {
        throw new Error("Missing the required parameter 'updateConfig' when calling tipConfigUpsert");
      }

      let pathParams = {
        'storeId': storeId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['oauth2'];
      let contentTypes = ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'];
      let accepts = ['application/json', 'text/json', 'application/xml', 'text/xml', 'Data', 'Message', 'ErrorCode', 'StackTrace'];
      let returnType = RestApiResultTipConfiguration;
      return this.apiClient.callApi(
        '/api/v1.0/stores/{storeId}/tipconfig', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
