/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Flipdish);
  }
}(this, function(expect, Flipdish) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Flipdish.BankAccountSummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BankAccountSummary', function() {
    it('should create an instance of BankAccountSummary', function() {
      // uncomment below and update the code to test BankAccountSummary
      //var instane = new Flipdish.BankAccountSummary();
      //expect(instance).to.be.a(Flipdish.BankAccountSummary);
    });

    it('should have the property Id (base name: "Id")', function() {
      // uncomment below and update the code to test the property Id
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property StoreNames (base name: "StoreNames")', function() {
      // uncomment below and update the code to test the property StoreNames
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property StoreIds (base name: "StoreIds")', function() {
      // uncomment below and update the code to test the property StoreIds
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property AccountState (base name: "AccountState")', function() {
      // uncomment below and update the code to test the property AccountState
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property CurrencyCode (base name: "CurrencyCode")', function() {
      // uncomment below and update the code to test the property CurrencyCode
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property StripeConnectedAccountInfo (base name: "StripeConnectedAccountInfo")', function() {
      // uncomment below and update the code to test the property StripeConnectedAccountInfo
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property AccountName (base name: "AccountName")', function() {
      // uncomment below and update the code to test the property AccountName
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property Iban (base name: "Iban")', function() {
      // uncomment below and update the code to test the property Iban
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property Swift (base name: "Swift")', function() {
      // uncomment below and update the code to test the property Swift
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property NationalClearingCode (base name: "NationalClearingCode")', function() {
      // uncomment below and update the code to test the property NationalClearingCode
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property PopulatedAccountFields (base name: "PopulatedAccountFields")', function() {
      // uncomment below and update the code to test the property PopulatedAccountFields
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property RejectionReason (base name: "RejectionReason")', function() {
      // uncomment below and update the code to test the property RejectionReason
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

    it('should have the property BusinessType (base name: "BusinessType")', function() {
      // uncomment below and update the code to test the property BusinessType
      //var instance = new Flipdish.BankAccountSummary();
      //expect(instance).to.be();
    });

  });

}));
