/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Flipdish);
  }
}(this, function(expect, Flipdish) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Flipdish.IndexPageBase();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('IndexPageBase', function() {
    it('should create an instance of IndexPageBase', function() {
      // uncomment below and update the code to test IndexPageBase
      //var instane = new Flipdish.IndexPageBase();
      //expect(instance).to.be.a(Flipdish.IndexPageBase);
    });

    it('should have the property AboutSectionEnabled (base name: "AboutSectionEnabled")', function() {
      // uncomment below and update the code to test the property AboutSectionEnabled
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property AboutSectionTitle (base name: "AboutSectionTitle")', function() {
      // uncomment below and update the code to test the property AboutSectionTitle
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property AboutSectionSubtitle (base name: "AboutSectionSubtitle")', function() {
      // uncomment below and update the code to test the property AboutSectionSubtitle
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property AboutSectionLeftTitle (base name: "AboutSectionLeftTitle")', function() {
      // uncomment below and update the code to test the property AboutSectionLeftTitle
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property AboutSectionLeftBody (base name: "AboutSectionLeftBody")', function() {
      // uncomment below and update the code to test the property AboutSectionLeftBody
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property AboutSectionRightTitle (base name: "AboutSectionRightTitle")', function() {
      // uncomment below and update the code to test the property AboutSectionRightTitle
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property AboutSectionRightBody (base name: "AboutSectionRightBody")', function() {
      // uncomment below and update the code to test the property AboutSectionRightBody
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property OpeningHoursEnabled (base name: "OpeningHoursEnabled")', function() {
      // uncomment below and update the code to test the property OpeningHoursEnabled
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property MenuPreviewEnabled (base name: "MenuPreviewEnabled")', function() {
      // uncomment below and update the code to test the property MenuPreviewEnabled
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property GalleryEnabled (base name: "GalleryEnabled")', function() {
      // uncomment below and update the code to test the property GalleryEnabled
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property TestimonialsEnabled (base name: "TestimonialsEnabled")', function() {
      // uncomment below and update the code to test the property TestimonialsEnabled
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property ContactFormEnabled (base name: "ContactFormEnabled")', function() {
      // uncomment below and update the code to test the property ContactFormEnabled
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property ContactFormEmail (base name: "ContactFormEmail")', function() {
      // uncomment below and update the code to test the property ContactFormEmail
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

    it('should have the property MapEnabled (base name: "MapEnabled")', function() {
      // uncomment below and update the code to test the property MapEnabled
      //var instance = new Flipdish.IndexPageBase();
      //expect(instance).to.be();
    });

  });

}));
