/**
 * Flipdish Open API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Flipdish);
  }
}(this, function(expect, Flipdish) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Flipdish.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('addUserNote', function() {
      it('should call addUserNote successfully', function(done) {
        //uncomment below and update the code to test addUserNote
        //instance.addUserNote(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUserToRole', function() {
      it('should call addUserToRole successfully', function(done) {
        //uncomment below and update the code to test addUserToRole
        //instance.addUserToRole(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('anonymizeUser', function() {
      it('should call anonymizeUser successfully', function(done) {
        //uncomment below and update the code to test anonymizeUser
        //instance.anonymizeUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('blockUserPhoneNumber', function() {
      it('should call blockUserPhoneNumber successfully', function(done) {
        //uncomment below and update the code to test blockUserPhoneNumber
        //instance.blockUserPhoneNumber(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createUserDeliveryLocation', function() {
      it('should call createUserDeliveryLocation successfully', function(done) {
        //uncomment below and update the code to test createUserDeliveryLocation
        //instance.createUserDeliveryLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPreviousOrderCountForStore', function() {
      it('should call getPreviousOrderCountForStore successfully', function(done) {
        //uncomment below and update the code to test getPreviousOrderCountForStore
        //instance.getPreviousOrderCountForStore(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRestaurantUserAccounts', function() {
      it('should call getRestaurantUserAccounts successfully', function(done) {
        //uncomment below and update the code to test getRestaurantUserAccounts
        //instance.getRestaurantUserAccounts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRestaurantUserStores', function() {
      it('should call getRestaurantUserStores successfully', function(done) {
        //uncomment below and update the code to test getRestaurantUserStores
        //instance.getRestaurantUserStores(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRoles', function() {
      it('should call getRoles successfully', function(done) {
        //uncomment below and update the code to test getRoles
        //instance.getRoles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRolesAndUnassignedRoles', function() {
      it('should call getRolesAndUnassignedRoles successfully', function(done) {
        //uncomment below and update the code to test getRolesAndUnassignedRoles
        //instance.getRolesAndUnassignedRoles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserById', function() {
      it('should call getUserById successfully', function(done) {
        //uncomment below and update the code to test getUserById
        //instance.getUserById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserDeliveryLocationsForAdmin', function() {
      it('should call getUserDeliveryLocationsForAdmin successfully', function(done) {
        //uncomment below and update the code to test getUserDeliveryLocationsForAdmin
        //instance.getUserDeliveryLocationsForAdmin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserNotes', function() {
      it('should call getUserNotes successfully', function(done) {
        //uncomment below and update the code to test getUserNotes
        //instance.getUserNotes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserOrderByIdForAdmin', function() {
      it('should call getUserOrderByIdForAdmin successfully', function(done) {
        //uncomment below and update the code to test getUserOrderByIdForAdmin
        //instance.getUserOrderByIdForAdmin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserOrdersForAdmin', function() {
      it('should call getUserOrdersForAdmin successfully', function(done) {
        //uncomment below and update the code to test getUserOrdersForAdmin
        //instance.getUserOrdersForAdmin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserSmsConversationItems', function() {
      it('should call getUserSmsConversationItems successfully', function(done) {
        //uncomment below and update the code to test getUserSmsConversationItems
        //instance.getUserSmsConversationItems(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('hideUserDeliveryLocation', function() {
      it('should call hideUserDeliveryLocation successfully', function(done) {
        //uncomment below and update the code to test hideUserDeliveryLocation
        //instance.hideUserDeliveryLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('markUserAsFraudulent', function() {
      it('should call markUserAsFraudulent successfully', function(done) {
        //uncomment below and update the code to test markUserAsFraudulent
        //instance.markUserAsFraudulent(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('markUserAsSuspicious', function() {
      it('should call markUserAsSuspicious successfully', function(done) {
        //uncomment below and update the code to test markUserAsSuspicious
        //instance.markUserAsSuspicious(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeFlipdishAccountIdForUser', function() {
      it('should call removeFlipdishAccountIdForUser successfully', function(done) {
        //uncomment below and update the code to test removeFlipdishAccountIdForUser
        //instance.removeFlipdishAccountIdForUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removeUserFromRole', function() {
      it('should call removeUserFromRole successfully', function(done) {
        //uncomment below and update the code to test removeUserFromRole
        //instance.removeUserFromRole(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resetMfa', function() {
      it('should call resetMfa successfully', function(done) {
        //uncomment below and update the code to test resetMfa
        //instance.resetMfa(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchFlipdishAccounts', function() {
      it('should call searchFlipdishAccounts successfully', function(done) {
        //uncomment below and update the code to test searchFlipdishAccounts
        //instance.searchFlipdishAccounts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('searchUsers', function() {
      it('should call searchUsers successfully', function(done) {
        //uncomment below and update the code to test searchUsers
        //instance.searchUsers(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendUserPushNotification', function() {
      it('should call sendUserPushNotification successfully', function(done) {
        //uncomment below and update the code to test sendUserPushNotification
        //instance.sendUserPushNotification(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('sendUserSms', function() {
      it('should call sendUserSms successfully', function(done) {
        //uncomment below and update the code to test sendUserSms
        //instance.sendUserSms(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setCustomerName', function() {
      it('should call setCustomerName successfully', function(done) {
        //uncomment below and update the code to test setCustomerName
        //instance.setCustomerName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setFlipdishAccountIdForUser', function() {
      it('should call setFlipdishAccountIdForUser successfully', function(done) {
        //uncomment below and update the code to test setFlipdishAccountIdForUser
        //instance.setFlipdishAccountIdForUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setUserDeliveryLocationCoordinates', function() {
      it('should call setUserDeliveryLocationCoordinates successfully', function(done) {
        //uncomment below and update the code to test setUserDeliveryLocationCoordinates
        //instance.setUserDeliveryLocationCoordinates(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setUserDeliveryLocationField', function() {
      it('should call setUserDeliveryLocationField successfully', function(done) {
        //uncomment below and update the code to test setUserDeliveryLocationField
        //instance.setUserDeliveryLocationField(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('setUserLanguage', function() {
      it('should call setUserLanguage successfully', function(done) {
        //uncomment below and update the code to test setUserLanguage
        //instance.setUserLanguage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('unblockUserPhoneNumber', function() {
      it('should call unblockUserPhoneNumber successfully', function(done) {
        //uncomment below and update the code to test unblockUserPhoneNumber
        //instance.unblockUserPhoneNumber(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
